# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 764422c57a2e9d4311648ad9fad44f1fe252327c6edf112551ab3d8a552c3889e3b0011a6ddf2e21ede9dfba059c5f7e6437df697c08b3afbd27e6e62d79d8bd

test:
  secret_key_base: 4dc726d75c9f491089f616e830b5e739ff6ef3bc911dc28f0520f4ccd91128223b6f68c685763edd77a3000e3a74d33105b819dc3fc3515bc61b8985602d205b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
